sonar.projectKey=tebuto_react-booking-widget_1010e87a-ca30-4917-a946-eeaa65dede4c

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.stories.tsx

sonar.exclusions=public/mockServiceWorker.js,dist/**,node_modules/**,src/mocks/**,src/components/examples/**,src/**/*.stories.tsx
sonar.coverage.exclusions=src/mocks/**,src/components/examples/**,src/**/*.stories.tsx,src/setupTests.ts,src/index.ts,src/**/index.ts,src/types.ts,src/api-types.ts,src/constants.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
