sonar.projectKey=tebuto_react-booking-widget_1010e87a-ca30-4917-a946-eeaa65dede4c
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.stories.tsx
sonar.exclusions=public/mockServiceWorker.js,dist/**,node_modules/**
